**Question 1:** What is a Support Vector Machine (SVM), and how does it work?

**Answer:**

A Support Vector Machine (SVM) is a supervised machine learning algorithm used for classification, regression, and outlier detection. It is particularly well known for its ability to perform binary classification with high accuracy, even in high-dimensional spaces.

At its core, a Support Vector Machine tries to find the best decision boundary (called a hyperplane) that separates data points of different classes in such a way that the margin (distance between the hyperplane and the nearest data points from each class) is maximized.

**How Does SVM Work**

Step-by-step:
* Input labeled training data.
* Map the data into a high-dimensional space (if needed, using the kernel trick).
* Find the optimal hyperplane that separates classes with the maximum margin.
* Classify new data points based on which side of the hyperplane they fall on.

**Question 2:** Explain the difference between Hard Margin and Soft Margin SVM.

**Answer:**

**Hard Margin SVM**

Concept:
* Assumes that the data is perfectly linearly separable — no overlap, no noise.
* Tries to find a hyperplane that separates the classes with the maximum margin and no misclassification is allowed.

Limitations:
* Very sensitive to outliers.
* Fails if the data isn’t perfectly separable (which is common in real-world data).

**Soft Margin SVM**

Concept:
* Introduced to handle noisy, non-linearly separable data.
* Allows some misclassifications (i.e., some points can be on the wrong side of the margin or even the hyperplane).
* Introduces slack variables (ξᵢ) to tolerate violations.

Adds a penalty:
* Balances between maximizing the margin and minimizing classification error.

**Key Differences Table**

| Feature                             | Hard Margin           | Soft Margin                 |
| ----------------------------------- | --------------------- | --------------------------- |
| **Data Type**                       | Perfectly separable   | Non-separable or noisy      |
| **Tolerance for Misclassification** |  No                  |  Yes                       |
| **Slack Variables**                 |  None                |  Used ($\xi_i$)            |
| **Outlier Sensitivity**             |  Very high          |  More robust              |
| **Use Case**                        | Clean, ideal datasets | Real-world, noisy datasets  |
| **Parameter $C$**                   | Not used              | Used to control flexibility |


**Question 3:** What is the Kernel Trick in SVM? Give one example of a kernel and explain its use case.

**Answer:**

The Kernel Trick is a mathematical technique that allows Support Vector Machines (SVMs) to solve non-linearly separable problems without explicitly mapping data to a higher-dimensional space.

Instead of transforming the data manually, the kernel trick uses a kernel function to compute the dot product of the data in the higher-dimensional space — efficiently and implicitly.

In many real-world problems, data cannot be separated by a straight line (or hyperplane) in its original space.

Rather than mapping all data points to a high-dimensional space (which is computationally expensive), the kernel trick lets us:
* Use non-linear boundaries in the original space.
* Keep the computation efficient and scalable.

**Example: Radial Basis Function (RBF) Kernel**

Formula:

    K(xi,xj)=exp(−γ ∥ xi −x j ∥^2 )

* γ controls the influence of a single training example.
  * Large γ: closer points matter more (tighter boundaries).
  * Small γ: points farther away still affect the decision boundary.

Use Case:
* RBF kernel is widely used for non-linear classification problems, especially when:
  * The data is not linearly separable.
  * You have complex, curved decision boundaries.
* Example: Image recognition, bioinformatics, handwriting classification.



**Question 4:** What is a Naïve Bayes Classifier, and why is it called “naïve”?

**Answer:**

A Naïve Bayes Classifier is a probabilistic machine learning algorithm used for classification tasks, based on Bayes' Theorem.

Bayes' Theorem provides a way to calculate the probability of a class given a set of features, using prior knowledge:

    P(C∣X) = P(X∣C)⋅P(C) / P(X)

Where:

* P(C∣X): Posterior probability of class C given data X
* P(X∣C): Likelihood of data X given class C
* P(C): Prior probability of class C
* P(X): Evidence (probability of the data, can be treated as a normalizing constant)

**Why is it called “naïve”**

It’s called naïve because it assumes that all features are conditionally independent of each other given the class.

That is:

    P(X1,X2,...,Xn∣C) = P(X1∣C)⋅P(X2∣C)⋅…⋅P(Xn∣C)

This assumption is rarely true in real-world data, but it greatly simplifies the computation, and surprisingly, Naïve Bayes often works very well in practice — especially with high-dimensional data like text.



**Question 5:** Describe the Gaussian, Multinomial, and Bernoulli Naïve Bayes variants.
When would you use each one?

**Answer:**

Gaussian Naive Bayes is for continuous data, Multinomial Naive Bayes is for discrete count data (like word frequencies in text), and Bernoulli Naive Bayes is for binary/boolean features.

**Gaussian Naive Bayes:**

Description:

Assumes features are normally distributed within each class and uses the mean and variance of each feature to calculate probabilities.

Use Cases:

Best for continuous data like sensor readings, measurements, or any data that can be reasonably approximated by a normal distribution.

Example:

Predicting house prices based on features like area, number of bedrooms, etc., where these features are continuous.

**Multinomial Naive Bayes:**

Description:

Uses the multinomial distribution to model discrete data, often used for text classification where features represent word counts or term frequencies.

Use Cases:

Text classification (spam detection, sentiment analysis), document categorization, where feature vectors represent the frequency of words or terms.

Example:

Classifying emails as spam or not spam based on the frequency of certain words.

**Bernoulli Naive Bayes:**

Description: Suitable for binary or boolean features (presence/absence of a feature).

Use Cases: Feature vectors where each feature represents a binary outcome, like whether a word appears in a document (1 for present, 0 for absent).

Example: Determining if a document is relevant to a topic based on the presence or absence of specific keywords.

**Dataset Info:**
* You can use any suitable datasets like Iris, Breast Cancer, or Wine from sklearn.datasets or a CSV file you have.

**Question 6:** Write a Python program to:
* Load the Iris dataset
* Train an SVM Classifier with a linear kernel
* Print the model's accuracy and support vectors.

(Include your Python code and output in the code box below.)

**Answer:**


In [123]:
# Load the Iris dataset
from sklearn.datasets import load_iris
iris = load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [124]:
X, y = iris.data, iris.target

In [125]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [126]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [127]:
# Split dataset into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [128]:
# Train an SVM Classifier with a linear kernel
from sklearn.svm import SVC
svm_model = SVC(kernel='linear')
svm_model

SVC(kernel='linear')

In [129]:
svm_model.fit(X_train, y_train)

SVC(kernel='linear')

In [130]:
# Predict on the test set
y_pred = svm_model.predict(X_test)
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0])

In [131]:
# Calculate accuracy
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
accuracy

1.0

**Question 7:** Write a Python program to:
* Load the Breast Cancer dataset
* Train a Gaussian Naïve Bayes model
* Print its classification report including precision, recall, and F1-score.

(Include your Python code and output in the code box below.)

**Answer:**


In [132]:
# Load the Breast Cancer dataset
from sklearn.datasets import load_breast_cancer
data = load_breast_cancer()
data

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [133]:
X, y = data.data, data.target

In [134]:
X

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [135]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [136]:
# Split dataset into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [137]:
# Train a Gaussian Naïve Bayes model
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb

GaussianNB()

In [138]:
gnb.fit(X_train, y_train)

GaussianNB()

In [139]:
# Predict on the test set
y_pred = gnb.predict(X_test)
y_pred

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0])

In [140]:
# Print the classification report
from sklearn.metrics import classification_report
cls_rep = classification_report(y_test, y_pred, target_names=data.target_names)
cls_rep

'              precision    recall  f1-score   support\n\n   malignant       0.93      0.90      0.92        63\n      benign       0.95      0.96      0.95       108\n\n    accuracy                           0.94       171\n   macro avg       0.94      0.93      0.94       171\nweighted avg       0.94      0.94      0.94       171\n'

In [141]:
print(cls_rep)

              precision    recall  f1-score   support

   malignant       0.93      0.90      0.92        63
      benign       0.95      0.96      0.95       108

    accuracy                           0.94       171
   macro avg       0.94      0.93      0.94       171
weighted avg       0.94      0.94      0.94       171



**Question 8:** Write a Python program to:
* Train an SVM Classifier on the Wine dataset using GridSearchCV to find the best C and gamma.
* Print the best hyperparameters and accuracy.

(Include your Python code and output in the code box below.)

**Answer:**


In [142]:
# Load the Wine dataset
from sklearn.datasets import load_wine
data = load_wine()
data

{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
         1.065e+03],
        [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
         1.050e+03],
        [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
         1.185e+03],
        ...,
        [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
         8.350e+02],
        [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
         8.400e+02],
        [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
         5.600e+02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1

In [143]:
X, y = data.data, data.target

In [144]:
X

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [145]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [146]:
# Split into train and test sets
from sklearn.model_selection import train_test_split, GridSearchCV
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [147]:
# Define the parameter grid
param_grid = {
    'C': [0.1, 1, 10, 100],
    'gamma': [0.001, 0.01, 0.1, 1],
    'kernel': ['rbf']
}
param_grid

{'C': [0.1, 1, 10, 100], 'gamma': [0.001, 0.01, 0.1, 1], 'kernel': ['rbf']}

In [148]:
# Set up the GridSearchCV
from sklearn.svm import SVC
grid = GridSearchCV(SVC(), param_grid, cv=5)
grid

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100], 'gamma': [0.001, 0.01, 0.1, 1],
                         'kernel': ['rbf']})

In [149]:
grid.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100], 'gamma': [0.001, 0.01, 0.1, 1],
                         'kernel': ['rbf']})

In [150]:
# Predict using the best model
best_model = grid.best_estimator_
best_model

SVC(C=10, gamma=0.001)

In [151]:
y_pred = best_model.predict(X_test)
y_pred

array([2, 0, 2, 0, 1, 0, 1, 2, 0, 0, 2, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       2, 2, 2, 1, 1, 2, 1, 0, 0, 1, 2, 0, 0, 0, 2, 2, 2, 1, 0, 1, 1, 0,
       2, 0, 2, 1, 2, 0, 1, 0, 0, 2])

In [152]:
grid.best_params_

{'C': 10, 'gamma': 0.001, 'kernel': 'rbf'}

In [153]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.7777777777777778

**Question 9:** Write a Python program to:
* Train a Naïve Bayes Classifier on a synthetic text dataset (e.g. using sklearn.datasets.fetch_20newsgroups).
* Print the model's ROC-AUC score for its predictions.

(Include your Python code and output in the code box below.)

**Answer:**


In [154]:
# Load a binary classification subset of 20 Newsgroups (e.g., 'sci.space' vs 'rec.sport.baseball')
from sklearn.datasets import fetch_20newsgroups
from sklearn.preprocessing import label_binarize
categories = ['sci.space', 'rec.sport.baseball']
categories

['sci.space', 'rec.sport.baseball']

In [155]:
newsgroups = fetch_20newsgroups(subset='all', categories=categories, remove=('headers', 'footers', 'quotes'))
newsgroups

{'data': ["\nDo you really have *that* much information on him?  Really?\n\n\nI don't know.  You tell me.  What percentage of players reach or \nexceed their MLE's *in their rookie season*?  We're talking about\n1993, you know.\n\n\nIf that were your purpose, maybe.  Offerman spent 1992 getting \nacclimated, if you will.  The Dodgers as a team paid a big price\nthat season.  Perhaps they will reap the benefits down the road.\nDo you really think they would have done what they did if they\nwere competing for a pennant?\n\n\nFor a stat-head, I'm amazed that you put any credence in spring\ntraining.  Did you notice who he got those 10 (!) hits off of, or\nare you going to tell me that it doesn't make a difference?\n\n\nWait a minute.  I missed something here.  First, forget Keith\nMitchell.  Are you saying that a kid who moves from AA to AAA\nand then does not improve would have been better off making a\ndirect leap to the majors?  If a player does well at AA and then\ndoes not improve at

In [156]:
# Split data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(newsgroups.data, newsgroups.target, test_size=0.3, random_state=42)

In [157]:
# Convert text to TF-IDF features
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

In [158]:
vectorizer

TfidfVectorizer()

In [159]:
# Train Multinomial Naïve Bayes
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()
nb.fit(X_train_tfidf, y_train)

MultinomialNB()

In [160]:
# Predict probabilities
y_prob = nb.predict_proba(X_test_tfidf)[:, 1]  # Probabilities for class 1
y_prob

array([0.03608658, 0.48917749, 0.0776338 , 0.04953747, 0.04407823,
       0.76642627, 0.28661905, 0.56362744, 0.51029693, 0.95358279,
       0.89662238, 0.23569828, 0.02952054, 0.64340455, 0.04248775,
       0.32681623, 0.93481505, 0.13879014, 0.73495024, 0.57541133,
       0.48917749, 0.87481254, 0.74507144, 0.05368594, 0.62885387,
       0.98300379, 0.05342084, 0.87035084, 0.61140725, 0.85773892,
       0.04766409, 0.02338035, 0.78173585, 0.13726128, 0.48917749,
       0.72935071, 0.8788252 , 0.02021326, 0.48917749, 0.13231998,
       0.48917749, 0.25491267, 0.79119593, 0.68471867, 0.22505504,
       0.48917749, 0.11782048, 0.42735494, 0.97342571, 0.0258229 ,
       0.84652595, 0.87182404, 0.11949911, 0.0766549 , 0.03633231,
       0.65843882, 0.14598771, 0.19415954, 0.92964894, 0.15707736,
       0.65110073, 0.80755501, 0.34403061, 0.81320666, 0.93954123,
       0.35528053, 0.03457323, 0.62211742, 0.80252247, 0.15136442,
       0.39865997, 0.9636186 , 0.12793611, 0.93042802, 0.68411

In [161]:
# Compute ROC-AUC
from sklearn.metrics import roc_auc_score
roc_auc = roc_auc_score(y_test, y_prob)
roc_auc

np.float64(0.9952927331568109)

In [162]:
print(f"ROC-AUC Score: {roc_auc:.2f}")

ROC-AUC Score: 1.00


**Question 10:** Imagine you’re working as a data scientist for a company that handles
email communications.

Your task is to automatically classify emails as Spam or Not Spam. The emails may
contain:
* Text with diverse vocabulary
* Potential class imbalance (far more legitimate emails than spam)
* Some incomplete or missing data

Explain the approach you would take to:
* Preprocess the data (e.g. text vectorization, handling missing data)
* Choose and justify an appropriate model (SVM vs. Naïve Bayes)
* Address class imbalance
* Evaluate the performance of your solution with suitable metrics

  And explain the business impact of your solution.

(Include your Python code and output in the code box below.)

**Answer:**


In [188]:
from sklearn.datasets import fetch_20newsgroups
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report, roc_auc_score
from sklearn.utils import resample
import numpy as np

In [190]:
# Step 1: Simulate Spam vs Not-Spam emails
categories = ['rec.sport.hockey', 'talk.politics.misc']  # Not spam vs Spam proxy
categories

['rec.sport.hockey', 'talk.politics.misc']

In [192]:
data = fetch_20newsgroups(subset='all', categories=categories, remove=('headers', 'footers', 'quotes'))
data

{'data': ['\n',
  '\n\n\n\n         When did Bill start doing endorsements?\n\n         Will he do the "Remington Shaver" ad?',
  'Have the rules for goalies\' equipment changed? It seems that e.g. glove\nhas become bigger and bigger all the time (and pads too), and the goalies are\nwearing "over size" jerseys. Am I dreaming? If you watch old photos or\nfilms let say about ten years back, I think the difference is quite obvious.\nWho is an expert on this, please let me know. (Or have the goalies become\nbigger?)',
  '\n\n\nSorry, Nelson, but you forgot to ask me. If you check the THN stats for\nKansas City, you\'ll find that Larry has been playing for the games, having\nplayed in 8 games in the period covered in the stats between 3/26 and the\n4/16 issue (1-3-4 with 13 PIM). Not exactly invisible.\n\n\nWell, having gotten to a chance to talk to him a few times, this isn\'t quite\naccurate. He injured his back (a disk injury) and did one stupid thing,\nwhich was to hide it from the Shar

In [193]:
X_raw = np.array(data.data)
y_raw = np.array(data.target)  # 0 = not spam, 1 = spam

In [196]:
X_raw

array(['\n',
       '\n\n\n\n         When did Bill start doing endorsements?\n\n         Will he do the "Remington Shaver" ad?',
       'Have the rules for goalies\' equipment changed? It seems that e.g. glove\nhas become bigger and bigger all the time (and pads too), and the goalies are\nwearing "over size" jerseys. Am I dreaming? If you watch old photos or\nfilms let say about ten years back, I think the difference is quite obvious.\nWho is an expert on this, please let me know. (Or have the goalies become\nbigger?)',
       ...,
       "How long can the Leafs play short-handed and still be expected to\nscore?  They did some fine penely-killing in the first (2 men down\nfor a couple of minutes at one point) but they just couldn't keep it \nup.  They spent virtually the entire game either short-handed or\njust coming off a penelty -- as soon as they'd get re-grouped, they're\npenalized again!\n \nSheesh -- like Gilmour said after the 1st -- you can't go calling \nevery little push an

In [195]:
y_raw

array([1, 1, 0, ..., 0, 1, 0])

In [197]:
# Step 2: Handle missing data
valid_indices = [i for i, text in enumerate(X_raw) if text.strip()]
X = X_raw[valid_indices]
y = y_raw[valid_indices]

In [199]:
# Step 3: Simulate class imbalance (more legit than spam)
X_spam = X[y == 1]
X_ham = X[y == 0]
y_spam = y[y == 1]
y_ham = y[y == 0]

In [205]:
X_ham_down, y_ham_down = resample(X_ham, y_ham, n_samples=len(X_spam)*2, random_state=42)

In [206]:
X_balanced = np.concatenate([X_spam, X_ham_down])
y_balanced = np.concatenate([y_spam, y_ham_down])

In [210]:
X_balanced

array(['\n\n\n\n         When did Bill start doing endorsements?\n\n         Will he do the "Remington Shaver" ad?',
       "Oh..\njust a note, my usually poor typing is made even more dificult by the \nsmall keyboard and mutiple connections I am piped through in order\nto access news while here in DC.\n\nI'm really not trying to irritate the spelling mavens :-)\n\nLUX ./. owen\n\n",
       '\n\nPerhaps you should change your name to Clayton "Mr Logic(NOT!)" Cramer!\nPlease give evidence of the above statement or shut up.  I believe that I\nmay have answered that elsewhere, amongst your other ravings.\n\n\n',
       ...,
       "\nThat's not inner calm.  It's boredom, and it's being spoiled.  The Arena's\nbeen as quiet as a church on many nights this year; too many of us just\ntake winning for granted.  It's been seemingly forever since the team\nlost, and we've forgotten what it's like to feel real excitement and\nsurprise at victory.\n\nWhile I'm glad to have the Pens doing so well, 

In [209]:
y_balanced

array([1, 1, 1, ..., 0, 0, 0])

In [213]:
# Step 4: Train-test split
X_train, X_test, y_train, y_test = train_test_split(X_balanced, y_balanced, test_size=0.3, stratify=y_balanced, random_state=42)

In [214]:
# Step 5: TF-IDF + Naive Bayes pipeline
vectorizer = TfidfVectorizer(stop_words='english', lowercase=True)
vectorizer

TfidfVectorizer(stop_words='english')

In [217]:
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

In [218]:
model = MultinomialNB()
model.fit(X_train_vec, y_train)

MultinomialNB()

In [220]:
# Step 6: Predict and evaluate
y_pred = model.predict(X_test_vec)
y_pred

array([0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,

In [221]:
y_prob = model.predict_proba(X_test_vec)[:, 1]
y_prob

array([6.61817717e-04, 2.72885400e-01, 1.59226370e-02, 1.04942272e-05,
       5.41657531e-01, 8.06744034e-02, 3.21056067e-01, 9.04713860e-01,
       9.60081188e-01, 9.12823541e-03, 6.35102119e-01, 1.60368463e-03,
       9.13414677e-01, 1.33156508e-03, 6.56902048e-01, 1.13351210e-01,
       9.06383780e-02, 4.46026908e-03, 3.63509565e-03, 3.39515437e-03,
       1.89783975e-03, 7.67089190e-02, 1.71087848e-02, 2.58535296e-02,
       2.69126921e-02, 6.27766460e-02, 3.42632277e-02, 4.24815536e-01,
       7.72395545e-01, 7.60605257e-03, 1.24003914e-03, 2.87994090e-03,
       2.25822583e-02, 5.87392391e-03, 2.06042031e-04, 1.46217588e-02,
       6.37089961e-01, 4.11487638e-02, 2.69126921e-02, 9.72808012e-01,
       8.70672971e-02, 8.00240065e-01, 5.27587965e-01, 8.28301582e-01,
       1.37038485e-02, 5.13629706e-03, 6.12199790e-03, 8.89572266e-03,
       7.17355373e-03, 6.37977521e-01, 9.13681012e-03, 2.18742761e-01,
       9.29055311e-01, 5.24985343e-02, 3.55470797e-01, 2.46586305e-03,
      

In [222]:
print(classification_report(y_test, y_pred, target_names=["Not Spam", "Spam"]))

              precision    recall  f1-score   support

    Not Spam       0.86      1.00      0.92       454
        Spam       1.00      0.67      0.81       227

    accuracy                           0.89       681
   macro avg       0.93      0.84      0.86       681
weighted avg       0.91      0.89      0.88       681



In [224]:
roc_auc = roc_auc_score(y_test, y_prob)
roc_auc

np.float64(0.9987191678472317)